import React, { useState, useEffect, useCallback, useContext } from "react";
import axios from "axios";
import { useNavigate, useLocation } from "react-router-dom";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import ipaddress from "../Components/IpAddress";
import { faCalendarAlt, faPlus, faRefresh, faSearch } from '@fortawesome/free-solid-svg-icons';
import { faEdit } from '@fortawesome/free-solid-svg-icons';
import { faTrash } from '@fortawesome/free-solid-svg-icons';
import { faSave } from '@fortawesome/free-solid-svg-icons';
import Button from 'react-bootstrap/Button';
import { Pagination } from "react-bootstrap";
import Swal from 'sweetalert2';
import {
    Row,
    Col,
    Input,
    FormGroup,
    Label,
    Card,
    CardBody,
    Modal,
    Table,
    ModalBody,
    ModalHeader,
} from "reactstrap";
import { toast } from "react-toastify";
import AuthContext from "../Components/AuthProvider";

export default function CurrencyRateMaster() {

    const styles = {
        overlay: {
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            backgroundColor: 'rgba(255, 255, 255, 0.8)',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 9999,
        }
    };

    const navigate = useNavigate();
    const {
        jwtToken,
        userId,
        branchId,
        companyid,
        isAuthenticated,
    } = useContext(AuthContext);

    useEffect(() => {
        if (!isAuthenticated) {
            navigate("/login?message=You need to be authenticated to access this page.");
        }
    }, [isAuthenticated, navigate]);

    const [loading, setLoading] = useState(false);

    // Search fields
    const [currencyId, setCurrencyId] = useState('');
    const [fromDate, setFromDate] = useState(null);
    const [toDate, setToDate] = useState(null);
    const [filteredData, setFilteredData] = useState([]);

    // Pagination states
    const [currentPage, setCurrentPage] = useState(1);
    const [itemsPerPage] = useState(20);

    // Modal states
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [flag, setFlag] = useState('add');

    // Form data - Currency ID will be auto-generated by backend
    const [formData, setFormData] = useState({
        companyId: companyid,
        branchId: branchId,
        currencyId: '', // Will be auto-generated by backend
        currencyDate: null,
        usdValue: 1.000,
        inrValue: '',
        createdBy: '',
        createdDate: null,
        editedBy: '',
        editedDate: null,
        approvedBy: '',
        approvedDate: null
    });

    const [formErrors, setFormErrors] = useState({
        currencyDate: '',
        inrValue: ''
    });

    // ==================== API CALLS ====================
const formatDateForBackend = (date) => {
    if (!date) return null;
    if (typeof date === 'string') return date;
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
};

// Utility function for parsing dates from backend
const parseDateFromBackend = (dateString) => {
    if (!dateString) return null;
    if (typeof dateString === 'string' && dateString.includes('-')) {
        const parts = dateString.split('-');
        if (parts.length === 3) {
            return new Date(parts[0], parts[1] - 1, parts[2]);
        }
    }
    return new Date(dateString);
};
    // 1. SEARCH API
     const search = (id, from, to) => {
        setLoading(true);
        const fromDateStr = from ? formatDateForBackend(from) : null;
        const toDateStr = to ? formatDateForBackend(to) : null;
        
        axios.get(`${ipaddress}currencyrate/search`, {
            params: {
                cid: companyid,
                bid: branchId,
                currencyId: id || '',
                fromDate: fromDateStr,
                toDate: toDateStr
            },
            headers: {
                Authorization: `Bearer ${jwtToken}`
            }
        })
        .then((response) => {
            setFilteredData(response.data);
            setLoading(false);
        })
        .catch((error) => {
            console.error("Search error:", error);
            toast.error("Error fetching data", { autoClose: 800 });
            setLoading(false);
        });
    };
    // const search = (id, from, to) => {
    //     setLoading(true);
    //     const fromDateStr = from ? from.getTime() : null;
    //     const toDateStr = to ? to.getTime() : null;
        
    //     axios.get(`${ipaddress}currencyrate/search`, {
    //         params: {
    //             cid: companyid,
    //             bid: branchId,
    //             currencyId: id || '',
    //             fromDate: fromDateStr,
    //             toDate: toDateStr
    //         },
    //         headers: {
    //             Authorization: `Bearer ${jwtToken}`
    //         }
    //     })
    //     .then((response) => {
    //         setFilteredData(response.data);
    //         setLoading(false);
    //     })
    //     .catch((error) => {
    //         console.error("Search error:", error);
    //         toast.error("Error fetching data", { autoClose: 800 });
    //         setLoading(false);
    //     });
    // };

    // 2. SAVE API (Add/Update)
    const handleSave = () => {
        let error = {};
        setLoading(true);
        
        // Currency ID is auto-generated, so no validation needed for it
        
        if (!formData.currencyDate) {
            error.currencyDate = "Currency date is required.";
            document.getElementById('currencyDate')?.classList.add('error-border');
        }

        if (!formData.inrValue) {
            error.inrValue = "INR Value is required.";
            document.getElementById('inrValue')?.classList.add('error-border');
        }

        if (Object.keys(error).length > 0) {
            setFormErrors(error);
            toast.error("Please fill in the required fields.", { autoClose: 1000 });
            setLoading(false);
            return;
        }

        const submitData = {
            ...formData,
            currencyDate: formData.currencyDate ? formData.currencyDate.getTime() : null
        };

        // Remove currencyId from submitData for add operation (backend will generate it)
        if (flag === 'add') {
            delete submitData.currencyId;
        }

        axios.post(`${ipaddress}currencyrate/save`, submitData, {
            params: {
                cid: companyid,
                bid: branchId,
                user: userId,
                flag: flag
            },
            headers: {
                Authorization: `Bearer ${jwtToken}`
            }
        })
        .then((response) => {
            toast.success('Data saved successfully', { autoClose: 800 });
            setFormErrors({ currencyDate: '', inrValue: '' });
            setLoading(false);
            document.getElementById('currencyDate')?.classList.remove('error-border');
            document.getElementById('inrValue')?.classList.remove('error-border');
                 const savedData = response.data;
        if (flag === 'add' && savedData.currencyId) {
            // Update formData with the new currencyId
            setFormData(prev => ({
                ...prev,
                currencyId: savedData.currencyId
            }));
            
            // Update the search field with new ID
            // setCurrencyId(savedData.currencyId);
            
            // Now search with the new ID
            search('', fromDate, toDate);
        } else {
            // For edit, just search with existing currencyId
            search('', fromDate, toDate);
        }
        
        setFlag("edit");
        // handleClose(); // Uncomment if you want to close modal
    })
        // .catch((error) => {
        //     console.error("Save error:", error);
        //     toast.error("Something went wrong", { autoClose: 800 });
        //     setLoading(false);
        // });
          .catch((error) => {
        console.error("Save error:", error);
        setLoading(false);
        
        // Handle error response from backend
        if (error.response) {
            // The request was made and the server responded with a status code
            // that falls out of the range of 2xx
            const errorMessage = error.response.data;
            
            if (error.response.status === 400) {
                // Bad Request - Show validation error
                toast.error(errorMessage || "Validation error occurred", { autoClose: 3000 });
            } else if (error.response.status === 404) {
                // Not Found
                toast.error(errorMessage || "Resource not found", { autoClose: 3000 });
            } else if (error.response.status === 500) {
                // Internal Server Error
                toast.error("Something went wrong on the server", { autoClose: 3000 });
            } else {
                toast.error(errorMessage || "An error occurred", { autoClose: 3000 });
            }
        } else if (error.request) {
            // The request was made but no response was received
            toast.error("No response from server. Please check your connection.", { autoClose: 3000 });
        } else {
            // Something happened in setting up the request that triggered an Error
            toast.error("Error setting up the request", { autoClose: 3000 });
        }
    });
    };

    // 3. GET DATA BY ID API (For Edit)
    const getData = (currId) => {
        setLoading(true);
        axios.get(`${ipaddress}currencyrate/getDataByCurrencyId`, {
            params: {
                cid: companyid,
                bid: branchId,
                currencyId: currId
            },
            headers: {
                Authorization: `Bearer ${jwtToken}`
            }
        })
        .then((response) => {
            const data = response.data;
            if (data.currencyDate) {
                data.currencyDate = new Date(data.currencyDate);
            }
            setFormData(data);
            setFlag('edit');
            setIsModalOpen(true);
            setLoading(false);
        })
        .catch((error) => {
            console.error("Get data error:", error);
            toast.error("Error fetching data", { autoClose: 800 });
            setLoading(false);
        });
    };

    // 4. DELETE API
    const deleteData = async (currId) => {
        const result = await Swal.fire({
            title: 'Are you sure you want to delete this record?',
            width: 'auto',
            position: 'top',
            showCancelButton: true,
            confirmButtonText: 'Yes',
            cancelButtonText: 'No',
            buttonsStyling: false,
        });

        if (result.isConfirmed) {
            setLoading(true);
            axios.post(`${ipaddress}currencyrate/deleteData`, null, {
                params: {
                    cid: companyid,
                    bid: branchId,
                    user: userId,
                    currencyId: currId
                },
                headers: {
                    Authorization: `Bearer ${jwtToken}`
                }
            })
            .then((response) => {
                const data = response.data;
                if (data === 'deleted') {
                    toast.success("Data deleted successfully!!", { autoClose: 800 });
                    search(currencyId, fromDate, toDate);
                } else {
                    toast.error("Record not found!!", { autoClose: 800 });
                }
                setLoading(false);
            })
            .catch((error) => {
                console.error("Delete error:", error);
                toast.error("Error deleting data", { autoClose: 800 });
                setLoading(false);
            });
        }
    };

    // ==================== HELPER FUNCTIONS ====================

    const handleReset = () => {
        setCurrencyId('');
        setFromDate(null);
        setToDate(null);
        search('', null, null);
    };

    const handleAddCurrency = () => {
        setFlag('add');
        setFormData({
            companyId: companyid,
            branchId: branchId,
            currencyId: '', // Will be auto-generated by backend
            currencyDate: null,
            usdValue: 1.000,
            inrValue: '',
            createdBy: '',
            createdDate: null,
            editedBy: '',
            editedDate: null,
            approvedBy: '',
            approvedDate: null
        });
        setFormErrors({ currencyDate: '', inrValue: '' });
        setIsModalOpen(true);
    };

    const handleClose = () => {
        setIsModalOpen(false);
        setFormErrors({ currencyDate: '', inrValue: '' });
        document.getElementById('currencyDate')?.classList.remove('error-border');
        document.getElementById('inrValue')?.classList.remove('error-border');
    };

  const handleFormDataChange = (event) => {
    const { name, value } = event.target;
    
    // For INR field, validate number format
    if (name === 'inrValue') {
        // Allow empty value
        if (value === '') {
            setFormData((prev) => ({ ...prev, [name]: '' }));
            setFormErrors((prev) => ({ ...prev, [name]: '' }));
            document.getElementById(name)?.classList.remove('error-border');
            return;
        }

        // Check if it's a valid number with up to 16 digits before decimal and 3 after
        const regex = /^\d{0,16}(\.\d{0,3})?$/;
        
        if (!regex.test(value)) {
            setFormErrors((prev) => ({ 
                ...prev, 
                [name]: 'Maximum 16 digits before decimal and 3 digits after decimal' 
            }));
            document.getElementById(name)?.classList.add('error-border');
            return;
        }

        setFormData((prev) => ({ ...prev, [name]: value }));
        setFormErrors((prev) => ({ ...prev, [name]: '' }));
        document.getElementById(name)?.classList.remove('error-border');
    } else {
        setFormData((prev) => ({ ...prev, [name]: value }));
        setFormErrors((prev) => ({ ...prev, [name]: '' }));
        document.getElementById(name)?.classList.remove('error-border');
    }
};

    const handleDateChange = (date) => {
        setFormData((prev) => ({ ...prev, currencyDate: date }));
        setFormErrors((prev) => ({ ...prev, currencyDate: '' }));
        document.getElementById('currencyDate')?.classList.remove('error-border');
    };

    const handleFormClear = () => {
        setFormData({
            companyId: companyid,
            branchId: branchId,
            currencyId: '',
            currencyDate: null,
            usdValue: 1.000,
            inrValue: '',
            createdBy: '',
            createdDate: null,
            editedBy: '',
            editedDate: null,
            approvedBy: '',
            approvedDate: null
        });
        setFormErrors({ currencyDate: '', inrValue: '' });
        document.getElementById('currencyDate')?.classList.remove('error-border');
        document.getElementById('inrValue')?.classList.remove('error-border');
        setFlag('add');
    };

    const formatDate = (timestamp) => {
        if (!timestamp) return '';
        const date = new Date(timestamp);
        return date.toLocaleDateString('en-GB', {
            day: '2-digit',
            month: '2-digit',
            year: 'numeric'
        });
    };

    // ==================== PAGINATION ====================

    useEffect(() => {
        search(currencyId, fromDate, toDate);
    }, []);

    const indexOfLastItem = currentPage * itemsPerPage;
    const indexOfFirstItem = indexOfLastItem - itemsPerPage;
    const currentItems = filteredData.slice(indexOfFirstItem, indexOfLastItem);
    const totalPages = Math.ceil(filteredData.length / itemsPerPage);

    const handlePageChange = (page) => {
        if (page >= 1 && page <= totalPages) {
            setCurrentPage(page);
        }
    };

    const displayPages = () => {
        const centerPageCount = 5;
        const middlePage = Math.floor(centerPageCount / 2);
        let startPage = currentPage - middlePage;
        let endPage = currentPage + middlePage;

        if (startPage < 1) {
            startPage = 1;
            endPage = Math.min(totalPages, centerPageCount);
        }

        if (endPage > totalPages) {
            endPage = totalPages;
            startPage = Math.max(1, totalPages - centerPageCount + 1);
        }

        return Array.from({ length: endPage - startPage + 1 }, (_, i) => startPage + i);
    };

    const setCurrentPageFun = () => {
        setCurrentPage(1);
    };

    // ==================== RENDER ====================

    return (
        <div className='Container'>
            {/* Loading Overlay */}
            {loading && (
                <div style={styles.overlay}>
                    <div className="loader">
                        <div className="truckWrapper">
                            <div className="truckBody">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 198 93" className="trucksvg">
                                    <path strokeWidth="3" stroke="#282828" fill="#F83D3D" d="M135 22.5H177.264C178.295 22.5 179.22 23.133 179.594 24.0939L192.33 56.8443C192.442 57.1332 192.5 57.4404 192.5 57.7504V89C192.5 90.3807 191.381 91.5 190 91.5H135C133.619 91.5 132.5 90.3807 132.5 89V25C132.5 23.6193 133.619 22.5 135 22.5Z"></path>
                                    <path strokeWidth="3" stroke="#282828" fill="#7D7C7C" d="M146 33.5H181.741C182.779 33.5 183.709 34.1415 184.078 35.112L190.538 52.112C191.16 53.748 189.951 55.5 188.201 55.5H146C144.619 55.5 143.5 54.3807 143.5 53V36C143.5 34.6193 144.619 33.5 146 33.5Z"></path>
                                    <path strokeWidth="2" stroke="#282828" fill="#282828" d="M150 65C150 65.39 149.763 65.8656 149.127 66.2893C148.499 66.7083 147.573 67 146.5 67C145.427 67 144.501 66.7083 143.873 66.2893C143.237 65.8656 143 65.39 143 65C143 64.61 143.237 64.1344 143.873 63.7107C144.501 63.2917 145.427 63 146.5 63C147.573 63 148.499 63.2917 149.127 63.7107C149.763 64.1344 150 64.61 150 65Z"></path>
                                    <rect strokeWidth="2" stroke="#282828" fill="#FFFCAB" rx="1" height="7" width="5" y="63" x="187"></rect>
                                    <rect strokeWidth="2" stroke="#282828" fill="#282828" rx="1" height="11" width="4" y="81" x="193"></rect>
                                    <rect strokeWidth="3" stroke="#282828" fill="#DFDFDF" rx="2.5" height="90" width="121" y="1.5" x="6.5"></rect>
                                    <rect strokeWidth="2" stroke="#282828" fill="#DFDFDF" rx="2" height="4" width="6" y="84" x="1"></rect>
                                </svg>
                            </div>
                            <div className="truckTires">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 30 30" className="tiresvg">
                                    <circle strokeWidth="3" stroke="#282828" fill="#282828" r="13.5" cy="15" cx="15"></circle>
                                    <circle fill="#DFDFDF" r="7" cy="15" cx="15"></circle>
                                </svg>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 30 30" className="tiresvg">
                                    <circle strokeWidth="3" stroke="#282828" fill="#282828" r="13.5" cy="15" cx="15"></circle>
                                    <circle fill="#DFDFDF" r="7" cy="15" cx="15"></circle>
                                </svg>
                            </div>
                            <div className="road"></div>
                            <svg xmlSpace="preserve" viewBox="0 0 453.459 453.459" xmlnsXlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Capa_1" version="1.1" fill="#000000" className="lampPost">
                                <path d="M252.882,0c-37.781,0-68.686,29.953-70.245,67.358h-6.917v8.954c-26.109,2.163-45.463,10.011-45.463,19.366h9.993c-1.65,5.146-2.507,10.54-2.507,16.017c0,28.956,23.558,52.514,52.514,52.514c28.956,0,52.514-23.558,52.514-52.514c0-5.478-0.856-10.872-2.506-16.017h9.992c0-9.354-19.352-17.204-45.463-19.366v-8.954h-6.149C200.189,38.779,223.924,16,252.882,16c29.952,0,54.32,24.368,54.32,54.32c0,28.774-11.078,37.009-25.105,47.437c-17.444,12.968-37.216,27.667-37.216,78.884v113.914h-0.797c-5.068,0-9.174,4.108-9.174,9.177c0,2.844,1.293,5.383,3.321,7.066c-3.432,27.933-26.851,95.744-8.226,115.459v11.202h45.75v-11.202c18.625-19.715-4.794-87.527-8.227-115.459c2.029-1.683,3.322-4.223,3.322-7.066c0-5.068-4.107-9.177-9.176-9.177h-0.795V196.641c0-43.174,14.942-54.283,30.762-66.043c14.793-10.997,31.559-23.461,31.559-60.277C323.202,31.545,291.656,0,252.882,0z M232.77,111.694c0,23.442-19.071,42.514-42.514,42.514c-23.442,0-42.514-19.072-42.514-42.514c0-5.531,1.078-10.957,3.141-16.017h78.747C231.693,100.736,232.77,106.162,232.77,111.694z"></path>
                            </svg>
                        </div>
                    </div>
                </div>
            )}

            {/* Main Content */}
            <div>
                <h5 className="pageHead" style={{ fontFamily: 'Your-Heading-Font', paddingLeft: '2%' }}>
                    <FontAwesomeIcon icon={faCalendarAlt} style={{ marginRight: '8px', color: 'black' }} />
                    Currency Rate
                </h5>

                <Card style={{ backgroundColor: "#F8F8F8" }}>
                    <CardBody>
                        {/* New Entry Button */}
                        <Row className="text-end">
                            <Col>
                                <Button type="button" onClick={handleAddCurrency} variant="outline-primary" style={{ marginTop: '0px', marginRight: 15 }}>
                                    <FontAwesomeIcon icon={faPlus} style={{ marginRight: '1px' }} />
                                    New Entry
                                </Button>
                            </Col>
                        </Row>
                        <hr />

                        {/* Search Section */}
                        <Row>
                            <Col md={2}>
                                <Label className="forlabel bold-label">Currency Id</Label>
                                <Input
                                    type="text"
                                    name="currencyId"
                                    id="currencyId"
                                    value={currencyId}
                                    onChange={(e) => setCurrencyId(e.target.value)}
                                    className="inputField"
                                    placeholder="Enter Currency Id"
                                />
                            </Col>
                            <Col md={2}>
                                <FormGroup>
                                    <Label className="forlabel bold-label" htmlFor="fromDate">From Date</Label>
                                    <div style={{ position: 'relative' }}>
                                        <DatePicker
                                            selected={fromDate}
                                            id="fromDate"
                                            onChange={(date) => setFromDate(date)}
                                            dateFormat="dd/MM/yyyy"
                                            placeholderText="Select From Date"
                                            className="form-control border-right-0 InputField"
                                            customInput={<Input style={{ width: '100%' }} />}
                                            wrapperClassName="custom-react-datepicker-wrapper"
                                        />
                                        <FontAwesomeIcon icon={faCalendarAlt} style={{ position: 'absolute', right: '10px', top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: '#6c757d' }} />
                                    </div>
                                </FormGroup>
                            </Col>
                            <Col md={2}>
                                <FormGroup>
                                    <Label className="forlabel bold-label" htmlFor="toDate">To Date</Label>
                                    <div style={{ position: 'relative' }}>
                                        <DatePicker
                                            selected={toDate}
                                            id="toDate"
                                            onChange={(date) => setToDate(date)}
                                            dateFormat="dd/MM/yyyy"
                                            placeholderText="Select To Date"
                                            className="form-control border-right-0 InputField"
                                            customInput={<Input style={{ width: '100%' }} />}
                                            wrapperClassName="custom-react-datepicker-wrapper"
                                        />
                                        <FontAwesomeIcon icon={faCalendarAlt} style={{ position: 'absolute', right: '10px', top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: '#6c757d' }} />
                                    </div>
                                </FormGroup>
                            </Col>
                            <Col md={3} style={{ marginTop: 24 }}>
                                <button
                                    className="btn btn-outline-success btn-margin newButton"
                                    style={{ fontSize: 12, marginRight: 5 }}
                                    onClick={() => { search(currencyId, fromDate, toDate); setCurrentPageFun(); }}
                                >
                                    <FontAwesomeIcon icon={faSearch} style={{ marginRight: '1px' }} />
                                    Search
                                </button>
                                <button
                                    className="btn btn-outline-danger btn-margin newButton"
                                    style={{ fontSize: 12 }}
                                    onClick={handleReset}
                                >
                                    <FontAwesomeIcon icon={faRefresh} style={{ marginRight: '1px' }} />
                                    Reset
                                </button>
                            </Col>
                        </Row>

                        {/* Table Section */}
                        {filteredData && filteredData.length > 0 && (
                            <>
                                <hr />
                                <div className="mt-1 table-responsive">
                                    <Table className="table table-bordered table-hover tableHeader">
                                        <thead className='tableHeader'>
                                            <tr style={{ fontWeight: 'bold', border: '2px solid black', fontSize: '17px' }}>
                                                <th className="text-center">Sr No</th>
                                                <th className="text-center">Currency Id</th>
                                                <th className="text-center">Currency Date</th>
                                                <th className="text-center">USD </th>
                                                <th className="text-center">INR </th>
                                                <th className="text-center">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {currentItems.map((item, index) => (
                                                <tr key={index} className='text-center'>
                                                    <td>{((currentPage - 1) * itemsPerPage) + index + 1}</td>
                                                    <td>{item.currencyId}</td>
                                                    <td>{formatDate(item.currencyDate)}</td>
                                                    <td>{item.usdValue}</td>
                                                    <td>{item.inrValue}</td>
                                                    <td>
                                                        <Button type="button" onClick={() => getData(item.currencyId)} variant="outline-primary" style={{ marginTop: '0px', marginRight: 15 }}>
                                                            <FontAwesomeIcon icon={faEdit} />
                                                        </Button>
                                                        <Button type="button" onClick={() => deleteData(item.currencyId)} variant="outline-danger" style={{ marginTop: '0px', marginRight: 15 }}>
                                                            <FontAwesomeIcon icon={faTrash} />
                                                        </Button>
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </Table>
                                </div>
                                
                                {/* Pagination */}
                                <Pagination style={{ display: 'flex', justifyContent: 'center', color: 'gray' }}>
                                    <Pagination.First onClick={() => handlePageChange(1)} />
                                    <Pagination.Prev onClick={() => handlePageChange(currentPage - 1)} disabled={currentPage === 1} />
                                    <Pagination.Ellipsis />
                                    {displayPages().map((pageNumber) => (
                                        <Pagination.Item key={pageNumber} active={pageNumber === currentPage} onClick={() => handlePageChange(pageNumber)}>
                                            {pageNumber}
                                        </Pagination.Item>
                                    ))}
                                    <Pagination.Ellipsis />
                                    <Pagination.Next onClick={() => handlePageChange(currentPage + 1)} disabled={currentPage === totalPages} />
                                    <Pagination.Last onClick={() => handlePageChange(totalPages)} />
                                </Pagination>
                            </>
                        )}
                    </CardBody>
                </Card>
            </div>

            {/* Modal for Add/Edit */}
            <Modal isOpen={isModalOpen} toggle={handleClose} style={{ maxWidth: '800px' }}>
                <ModalHeader toggle={handleClose} style={{
                    background: 'radial-gradient(circle farthest-corner at 48.4% 47.5%, rgba(122,183,255,1) 0%, rgba(21,83,161,1) 90%)',
                    backgroundSize: 'cover',
                    backgroundRepeat: 'no-repeat',
                    backgroundPosition: 'center',
                    color: 'white'
                }}>
                    {flag === 'add' ? (
                        <h5 className="pageHead" style={{ fontFamily: 'Your-Heading-Font', color: 'white' }}>
                            <FontAwesomeIcon icon={faPlus} style={{ marginRight: '8px' }} /> Add Currency Rate Details
                        </h5>
                    ) : (
                        <h5 className="pageHead" style={{ fontFamily: 'Your-Heading-Font', color: 'white' }}>
                            <FontAwesomeIcon icon={faEdit} style={{ marginRight: '8px' }} /> Edit Currency Rate Details
                        </h5>
                    )}
                </ModalHeader>
                <ModalBody style={{ backgroundImage: 'url(https://img.freepik.com/free-vector/gradient-wavy-background_23-2149123392.jpg?t=st=1694859409~exp=1694860009~hmac=b397945a9c2d45405ac64956165f76bd10a0eff99334c52cd4c88d4162aad58e)', backgroundSize: 'cover' }}>
                    
                    {/* Currency ID - Auto-generated, shown as read-only in add mode */}
                    <Row>
                        <Col md={6}>
                            <Label style={{ fontSize: '14px' }} className="forlabel" for="currencyId">
                                Currency Id {flag === 'add' }
                                {flag === 'edit' && <span style={{ color: 'red' }}>*</span>}
                            </Label>
                            <Input
                                type="text"
                                name="currencyId"
                                id="currencyId"
                                value={formData.currencyId || (flag === 'add' ? 'Currency ID' : '')}
                                className="inputField"
                                disabled
                                style={{ backgroundColor: '#f5f5f5', cursor: 'not-allowed' }}
                            />
                           
                        </Col>
                        <Col md={6}>
                            <FormGroup>
                                <label className="forlabel bold-label" htmlFor="currencyDate">
                                    Currency Date <span style={{ color: 'red' }}>*</span>
                                </label>
                                <div style={{ position: 'relative' }}>
                                    <DatePicker
                                        selected={formData.currencyDate}
                                        id="currencyDate"
                                        onChange={handleDateChange}
                                        dateFormat="dd/MM/yyyy "
                                        placeholderText="Select Currency Date"
                                        className="form-control border-right-0 InputField"
                                        customInput={<Input style={{ width: '100%' }} />}
                                        wrapperClassName="custom-react-datepicker-wrapper"
                                     
                                    />
                                    <FontAwesomeIcon icon={faCalendarAlt} style={{ position: 'absolute', right: '10px', top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: '#6c757d' }} />
                                </div>
                                <div style={{ color: 'red' }} className="error-message">{formErrors.currencyDate}</div>
                            </FormGroup>
                        </Col>
                    </Row>

                    {/* USD and INR Values */}
                    <Row style={{ marginTop: '15px' }}>
                        <Col md={6}>
                            <Label style={{ fontSize: '14px' }} className="forlabel" for="usdValue">USD 
                            </Label>
                            <Input
                                type="number"
                                name="usdValue"
                                id="usdValue"
                                value={formData.usdValue}
                                onChange={handleFormDataChange}
                                className="inputField"
                                step="0.001"
                                readOnly
                                disabled
                            />
                           
                        </Col>
                        <Col md={6}>
                            <Label style={{ fontSize: '14px' }} className="forlabel" for="inrValue">
                                INR 
                                 <span style={{ color: 'red' }}>*</span>
                            </Label>
                            <Input
                                type="tex"
                                name="inrValue"
                                id="inrValue"
                                value={formData.inrValue}
                                onChange={handleFormDataChange}
                                className="inputField"
                                placeholder="Enter INR Value"
                              
                                 maxLength="20" 
                            />
                            <div style={{ color: 'red' }} className="error-message">{formErrors.inrValue}</div>
                        </Col>
                    </Row>

                    <hr />

                    {/* Buttons */}
                    <Row className="text-center" style={{ marginTop: 25 }}>
                        <Col>
                            <Button type="button" onClick={handleSave} className="newButton" variant="outline-success" style={{ marginTop: '0px', marginRight: 15 }}>
                                <FontAwesomeIcon icon={faSave} style={{ marginRight: '1px' }} />
                                Submit
                            </Button>
                            {flag === 'add' && (
                                <Button type="button" onClick={handleFormClear} className="newButton" variant="outline-danger" style={{ marginTop: '0px' }}>
                                    <FontAwesomeIcon icon={faRefresh} style={{ marginRight: '1px' }} />
                                    Clear
                                </Button>
                            )}
                        </Col>
                    </Row>
                </ModalBody>
            </Modal>
        </div>
    );
}